# Site settings
title: "Minor Vices"
description: >-
  Minor Vices is a no-nonsense, NYC based design studio founded out of the
  desire to work with great brands and great teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: "hey@minorvices.com"
tel: "+1 646 694 0062"
header_nav_page_paths:
  - "about.md"
  - "work.md"
  - "contact.md"

# Build settings
markdown: "kramdown"
plugins:
  - "jekyll-seo-tag"

# Exclusions
# The following items will be excluding from processing by default.
# To override uncomment and edit as needed.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
